version: '1'

services:
    web:
        container_name: node_restapi
        restart: always
        build: .
        ports:
            - "80:80"
        links:
            - "mysql"

    mysql:
        container_name: mysql
        environment:
          MYSQL_DATABASE: 'bdpaises'
          MYSQL_USER: 'secros'
          MYSQL_PASSWORD: 'sovier'
          MYSQL_ROOT_PASSWORD: 'sovier'

        image: mysql
        ports:
          - "3306:3306"
        volumes:
          - mysql:/var/lib/mysql
volumes:
  mysql:

