version: '2'
services:
   api:
     image: secros18/node-restapi:latest
     build:
       context: .
       dockerfile: Dockerfile
     restart: always
     ports:
        - "3000:3000"
     networks:
       netcoreconcepts_mi_red:
         ipv4_address: 172.18.0.4
     environment:
      - SERVICIO2_URL=https://172.18.0.2:443
   web:
     image: secros18/angular-app:latest
     ports:
       - "4200:4200"
     networks:
        netcoreconcepts_mi_red:
          ipv4_address: 172.18.0.5
networks:
  netcoreconcepts_mi_red:
    external: true


